
POST http://192.168.23.130:8080/api/v1/members/login HTTP/1.1
content-type: application/json
Authorization: Bearer eMVofOE0EQS3BNEfG09i2If0qwV8FxwQCeiWdqGovx8RRmvhY0oLgk582bkgYhfeeBvB/pWNlpYeQftDtg==

{
 "mbrId" : "manmanyi@naver.com",
 "mbrPwd" : "qwer1134!@#",
 "isKeepLogin" :0
}

#######################
POST http://192.168.23.130:8080/api/v1/users/anonymous HTTP/1.1
content-type: application/json

{
 "fnlAppVer" : "11111.00",
 "dvcOsCd" : "IO",
 "pshTkn" : "aaabbbccc",
 "adPushFg" : 0
}
